version: '3'
services:
    app:
        image: 'jc21/nginx-proxy-manager:latest'
        container_name: nginx-manager
        ports:
            - '80:80'
            - '81:81'
            - '443:443'
        volumes:
            - ./confdir/config.json:/app/config/production.json
            - ./workdir:/data
            - ./letsencrypt:/etc/letsencrypt
    db:
        image: 'jc21/mariadb-aria:10.4'
        container_name: nginx-manager-db
        env_file:
            - db.env
        volumes:
            - ./workdir/mysql:/var/lib/mysql
