version: '3'
services:
    app:
        image: 'jc21/nginx-proxy-manager:2.9.22'
        container_name: nginx-manager
        restart: unless-stopped
        ports:
            - '80:80'
            - '81:81'
            - '443:443'
        volumes:
            - ./confdir/config.json:/app/config/production.json
            - ./confdir/letsencrypt:/etc/letsencrypt
            - ./workdir:/data
        healthcheck:
            test: [ "CMD", "/bin/check-health" ]
            interval: 10s
            timeout: 3s
    db:
        image: 'jc21/mariadb-aria:10.4'
        container_name: nginx-manager-db
        restart: unless-stopped
        env_file:
            - db.env
        volumes:
            - ./workdir/mysql:/var/lib/mysql
