version: '3.3'
services:
    heimdall:
        image: ghcr.io/linuxserver/heimdall
        container_name: heimdall
        environment:
            - PUID=${PUID}
            - PGID=${GUID}
            - TZ=Europe/Berlin
        volumes:
            - './confdir:/config'
        ports:
            - "8888:80"
            - "4443:443"
        restart: unless-stopped
