version: '3.3'
services:
    pihole:
        image: 'pihole/pihole:latest'
        container_name: pihole
        ports:
            - '53:53/tcp'
            - '53:53/udp'
            - '8080:80'
            - '444:443'
        environment:
            - TZ=Europe/Berlin
        volumes:
            - './confdir/etc-pihole/:/etc/pihole/'
            - './confdir/etc-dnsmasq.d/:/etc/dnsmasq.d/'
        dns:
            - 127.0.0.1
            - 1.1.1.1
        restart: unless-stopped
