version: '3.3'
services:
    pihole:
        image: 'pihole/pihole:latest'
        container_name: pihole
        ports:
            - '53:53/tcp'
            - '53:53/udp'
<<<<<<< HEAD
            - '80:80'
=======
            - '8080:80'
>>>>>>> a2d79c615d00365b95881266e9af37b16d534567
            - '443:443'
        environment:
            - TZ=Europe/Berlin
        volumes:
            - './confdir/etc-pihole/:/etc/pihole/'
            - './confdir/etc-dnsmasq.d/:/etc/dnsmasq.d/'
        dns:
            - 127.0.0.1
            - 1.1.1.1
        restart: unless-stopped
