version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    environment:
      - WATCHTOWER_CLEANUP=true
      - TZ=Europe/Berlin
      - WATCHTOWER_POLL_INTERVAL=43200
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: unless-stopped
