version: '3'
services:
    adguard-home:
        container_name: adguard-home
        image: adguard/adguardhome
        restart: on-failure

        volumes:
            - './workdir:/opt/adguardhome/work'
            - './confdir:/opt/adguardhome/conf'

        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "3000:3000"
