concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
    session_timeout = 1800

[[runners]]
    name = "runner_3"
    url = "$HOST_URL:$WEBSERVER_PORT"
    id = 3
    token = "$TOKEN"
    executor = "docker"
    [runners.cache]
        MaxUploadedArchiveSize = 0
    [runners.docker]
        tls_verify = false
        image = "docker:20.10.16"
        privileged = true
        disable_entrypoint_overwrite = false
        oom_kill_disable = false
        disable_cache = false
        volumes = ["/cache"]
        shm_size = 0
