version: "3.7"

services:
    node-red:
        image: nodered/node-red:2.2.2
        container_name: node-red
        depends_on:
            - homebridge
        environment:
            - TZ=Europe/Berlin
        ports:
            - "1880:1880"
        network_mode: host
        restart: unless-stopped
        volumes:
            - ./data:/data

