version: '3.7'
services:
    jdownloader-vpn:
        container_name: jdownloader-vpn
        image: plusminus/jdownloader2-headless:alpine
        restart: unless-stopped
        network_mode: "service:vpn"
        stdin_open: true
        tty: true
        depends_on:
            - vpn
        volumes:
            - "${DOWNLOAD_VOLUME_PATH}"
            - "${JDL_CONF_VOLUME_PATH}"
    vpn:
        container_name: vpn
        image: dperson/openvpn-client:latest
        cap_add:
            - net_admin
        dns:
            - 1.1.1.1
        environment:
            TZ: 'Europe/Berlin'
        networks:
            - default
        read_only: true
        tmpfs:
            - /run
            - /tmp
        restart: unless-stopped
        security_opt:
            - label:disable
        stdin_open: true
        tty: true
        volumes:
            - /dev/net:/dev/net:z
            - "${VPN_CONF_VOLUME_PATH}"
networks:
    default:
